// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: users.proto

package users

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrepareAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareAuthRequest) Reset() {
	*x = PrepareAuthRequest{}
	mi := &file_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareAuthRequest) ProtoMessage() {}

func (x *PrepareAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareAuthRequest.ProtoReflect.Descriptor instead.
func (*PrepareAuthRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{0}
}

type PrepareAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareAuthResponse) Reset() {
	*x = PrepareAuthResponse{}
	mi := &file_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareAuthResponse) ProtoMessage() {}

func (x *PrepareAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareAuthResponse.ProtoReflect.Descriptor instead.
func (*PrepareAuthResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{1}
}

func (x *PrepareAuthResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ResolveAuthKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveAuthKeyRequest) Reset() {
	*x = ResolveAuthKeyRequest{}
	mi := &file_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAuthKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAuthKeyRequest) ProtoMessage() {}

func (x *ResolveAuthKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAuthKeyRequest.ProtoReflect.Descriptor instead.
func (*ResolveAuthKeyRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveAuthKeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ResolveAuthKeyResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Valid             bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	ProvisionalUserId string                 `protobuf:"bytes,2,opt,name=provisional_user_id,json=provisionalUserId,proto3" json:"provisional_user_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResolveAuthKeyResponse) Reset() {
	*x = ResolveAuthKeyResponse{}
	mi := &file_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveAuthKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveAuthKeyResponse) ProtoMessage() {}

func (x *ResolveAuthKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveAuthKeyResponse.ProtoReflect.Descriptor instead.
func (*ResolveAuthKeyResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveAuthKeyResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ResolveAuthKeyResponse) GetProvisionalUserId() string {
	if x != nil {
		return x.ProvisionalUserId
	}
	return ""
}

type CreateProvisionalUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProvisionalUserRequest) Reset() {
	*x = CreateProvisionalUserRequest{}
	mi := &file_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProvisionalUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProvisionalUserRequest) ProtoMessage() {}

func (x *CreateProvisionalUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProvisionalUserRequest.ProtoReflect.Descriptor instead.
func (*CreateProvisionalUserRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{4}
}

type CreateProvisionalUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProvisionalUserResponse) Reset() {
	*x = CreateProvisionalUserResponse{}
	mi := &file_users_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProvisionalUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProvisionalUserResponse) ProtoMessage() {}

func (x *CreateProvisionalUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProvisionalUserResponse.ProtoReflect.Descriptor instead.
func (*CreateProvisionalUserResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{5}
}

func (x *CreateProvisionalUserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type VerifyPhoneRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PhoneE164         string                 `protobuf:"bytes,1,opt,name=phone_e164,json=phoneE164,proto3" json:"phone_e164,omitempty"`
	ProvisionalUserId string                 `protobuf:"bytes,2,opt,name=provisional_user_id,json=provisionalUserId,proto3" json:"provisional_user_id,omitempty"`
	AuthKey           string                 `protobuf:"bytes,3,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"`
	Platform          string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VerifyPhoneRequest) Reset() {
	*x = VerifyPhoneRequest{}
	mi := &file_users_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPhoneRequest) ProtoMessage() {}

func (x *VerifyPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPhoneRequest.ProtoReflect.Descriptor instead.
func (*VerifyPhoneRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyPhoneRequest) GetPhoneE164() string {
	if x != nil {
		return x.PhoneE164
	}
	return ""
}

func (x *VerifyPhoneRequest) GetProvisionalUserId() string {
	if x != nil {
		return x.ProvisionalUserId
	}
	return ""
}

func (x *VerifyPhoneRequest) GetAuthKey() string {
	if x != nil {
		return x.AuthKey
	}
	return ""
}

func (x *VerifyPhoneRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type VerifyPhoneResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token           string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	IsNewUser       bool                   `protobuf:"varint,3,opt,name=is_new_user,json=isNewUser,proto3" json:"is_new_user,omitempty"`
	InitialPassword string                 `protobuf:"bytes,4,opt,name=initial_password,json=initialPassword,proto3" json:"initial_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VerifyPhoneResponse) Reset() {
	*x = VerifyPhoneResponse{}
	mi := &file_users_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPhoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPhoneResponse) ProtoMessage() {}

func (x *VerifyPhoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPhoneResponse.ProtoReflect.Descriptor instead.
func (*VerifyPhoneResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyPhoneResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyPhoneResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *VerifyPhoneResponse) GetIsNewUser() bool {
	if x != nil {
		return x.IsNewUser
	}
	return false
}

func (x *VerifyPhoneResponse) GetInitialPassword() string {
	if x != nil {
		return x.InitialPassword
	}
	return ""
}

type CheckAuthTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAuthTokenRequest) Reset() {
	*x = CheckAuthTokenRequest{}
	mi := &file_users_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAuthTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAuthTokenRequest) ProtoMessage() {}

func (x *CheckAuthTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAuthTokenRequest.ProtoReflect.Descriptor instead.
func (*CheckAuthTokenRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{8}
}

func (x *CheckAuthTokenRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type CheckAuthTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAuthTokenResponse) Reset() {
	*x = CheckAuthTokenResponse{}
	mi := &file_users_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAuthTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAuthTokenResponse) ProtoMessage() {}

func (x *CheckAuthTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAuthTokenResponse.ProtoReflect.Descriptor instead.
func (*CheckAuthTokenResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{9}
}

func (x *CheckAuthTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CheckAuthTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LoginWithPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneE164     string                 `protobuf:"bytes,1,opt,name=phone_e164,json=phoneE164,proto3" json:"phone_e164,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginWithPasswordRequest) Reset() {
	*x = LoginWithPasswordRequest{}
	mi := &file_users_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginWithPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithPasswordRequest) ProtoMessage() {}

func (x *LoginWithPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithPasswordRequest.ProtoReflect.Descriptor instead.
func (*LoginWithPasswordRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{10}
}

func (x *LoginWithPasswordRequest) GetPhoneE164() string {
	if x != nil {
		return x.PhoneE164
	}
	return ""
}

func (x *LoginWithPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginWithPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginWithPasswordResponse) Reset() {
	*x = LoginWithPasswordResponse{}
	mi := &file_users_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginWithPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginWithPasswordResponse) ProtoMessage() {}

func (x *LoginWithPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginWithPasswordResponse.ProtoReflect.Descriptor instead.
func (*LoginWithPasswordResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{11}
}

func (x *LoginWithPasswordResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginWithPasswordResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ChangePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_users_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{12}
}

func (x *ChangePasswordRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ChangePasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordResponse) Reset() {
	*x = ChangePasswordResponse{}
	mi := &file_users_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResponse) ProtoMessage() {}

func (x *ChangePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResponse.ProtoReflect.Descriptor instead.
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{13}
}

func (x *ChangePasswordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_users_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateUserRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserId              string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName         *string                `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	Locale              *string                `protobuf:"bytes,3,opt,name=locale,proto3,oneof" json:"locale,omitempty"`
	Timezone            *string                `protobuf:"bytes,4,opt,name=timezone,proto3,oneof" json:"timezone,omitempty"`
	BirthDate           *string                `protobuf:"bytes,5,opt,name=birth_date,json=birthDate,proto3,oneof" json:"birth_date,omitempty"`
	Sex                 *string                `protobuf:"bytes,6,opt,name=sex,proto3,oneof" json:"sex,omitempty"`
	OnboardingCompleted *bool                  `protobuf:"varint,7,opt,name=onboarding_completed,json=onboardingCompleted,proto3,oneof" json:"onboarding_completed,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_users_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *UpdateUserRequest) GetLocale() string {
	if x != nil && x.Locale != nil {
		return *x.Locale
	}
	return ""
}

func (x *UpdateUserRequest) GetTimezone() string {
	if x != nil && x.Timezone != nil {
		return *x.Timezone
	}
	return ""
}

func (x *UpdateUserRequest) GetBirthDate() string {
	if x != nil && x.BirthDate != nil {
		return *x.BirthDate
	}
	return ""
}

func (x *UpdateUserRequest) GetSex() string {
	if x != nil && x.Sex != nil {
		return *x.Sex
	}
	return ""
}

func (x *UpdateUserRequest) GetOnboardingCompleted() bool {
	if x != nil && x.OnboardingCompleted != nil {
		return *x.OnboardingCompleted
	}
	return false
}

type UserResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PhoneE164             string                 `protobuf:"bytes,2,opt,name=phone_e164,json=phoneE164,proto3" json:"phone_e164,omitempty"`
	PhoneVerifiedAt       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=phone_verified_at,json=phoneVerifiedAt,proto3" json:"phone_verified_at,omitempty"`
	CreatedAt             *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	OnboardingCompletedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=onboarding_completed_at,json=onboardingCompletedAt,proto3,oneof" json:"onboarding_completed_at,omitempty"`
	Locale                string                 `protobuf:"bytes,7,opt,name=locale,proto3" json:"locale,omitempty"`
	Timezone              string                 `protobuf:"bytes,8,opt,name=timezone,proto3" json:"timezone,omitempty"`
	DisplayName           string                 `protobuf:"bytes,9,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	BirthDate             string                 `protobuf:"bytes,10,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	Sex                   string                 `protobuf:"bytes,11,opt,name=sex,proto3" json:"sex,omitempty"`
	IsAdmin               bool                   `protobuf:"varint,12,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_users_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{16}
}

func (x *UserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserResponse) GetPhoneE164() string {
	if x != nil {
		return x.PhoneE164
	}
	return ""
}

func (x *UserResponse) GetPhoneVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PhoneVerifiedAt
	}
	return nil
}

func (x *UserResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *UserResponse) GetOnboardingCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OnboardingCompletedAt
	}
	return nil
}

func (x *UserResponse) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *UserResponse) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *UserResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UserResponse) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *UserResponse) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *UserResponse) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_users_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{17}
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserType      string                 `protobuf:"bytes,3,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_users_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{18}
}

func (x *ValidateTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateTokenResponse) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

type CheckProvisionalOrphansRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProvisionalUserId string                 `protobuf:"bytes,1,opt,name=provisional_user_id,json=provisionalUserId,proto3" json:"provisional_user_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CheckProvisionalOrphansRequest) Reset() {
	*x = CheckProvisionalOrphansRequest{}
	mi := &file_users_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckProvisionalOrphansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckProvisionalOrphansRequest) ProtoMessage() {}

func (x *CheckProvisionalOrphansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckProvisionalOrphansRequest.ProtoReflect.Descriptor instead.
func (*CheckProvisionalOrphansRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{19}
}

func (x *CheckProvisionalOrphansRequest) GetProvisionalUserId() string {
	if x != nil {
		return x.ProvisionalUserId
	}
	return ""
}

type CheckProvisionalOrphansResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOrphan      bool                   `protobuf:"varint,1,opt,name=is_orphan,json=isOrphan,proto3" json:"is_orphan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckProvisionalOrphansResponse) Reset() {
	*x = CheckProvisionalOrphansResponse{}
	mi := &file_users_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckProvisionalOrphansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckProvisionalOrphansResponse) ProtoMessage() {}

func (x *CheckProvisionalOrphansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckProvisionalOrphansResponse.ProtoReflect.Descriptor instead.
func (*CheckProvisionalOrphansResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{20}
}

func (x *CheckProvisionalOrphansResponse) GetIsOrphan() bool {
	if x != nil {
		return x.IsOrphan
	}
	return false
}

type DeleteProvisionalUserRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProvisionalUserId string                 `protobuf:"bytes,1,opt,name=provisional_user_id,json=provisionalUserId,proto3" json:"provisional_user_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeleteProvisionalUserRequest) Reset() {
	*x = DeleteProvisionalUserRequest{}
	mi := &file_users_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProvisionalUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProvisionalUserRequest) ProtoMessage() {}

func (x *DeleteProvisionalUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProvisionalUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteProvisionalUserRequest) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteProvisionalUserRequest) GetProvisionalUserId() string {
	if x != nil {
		return x.ProvisionalUserId
	}
	return ""
}

type DeleteProvisionalUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProvisionalUserResponse) Reset() {
	*x = DeleteProvisionalUserResponse{}
	mi := &file_users_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProvisionalUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProvisionalUserResponse) ProtoMessage() {}

func (x *DeleteProvisionalUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProvisionalUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteProvisionalUserResponse) Descriptor() ([]byte, []int) {
	return file_users_proto_rawDescGZIP(), []int{22}
}

var File_users_proto protoreflect.FileDescriptor

const file_users_proto_rawDesc = "" +
	"\n" +
	"\vusers.proto\x12\x05users\x1a\x1fgoogle/protobuf/timestamp.proto\"\x14\n" +
	"\x12PrepareAuthRequest\"'\n" +
	"\x13PrepareAuthResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\")\n" +
	"\x15ResolveAuthKeyRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"^\n" +
	"\x16ResolveAuthKeyResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12.\n" +
	"\x13provisional_user_id\x18\x02 \x01(\tR\x11provisionalUserId\"\x1e\n" +
	"\x1cCreateProvisionalUserRequest\"/\n" +
	"\x1dCreateProvisionalUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x9a\x01\n" +
	"\x12VerifyPhoneRequest\x12\x1d\n" +
	"\n" +
	"phone_e164\x18\x01 \x01(\tR\tphoneE164\x12.\n" +
	"\x13provisional_user_id\x18\x02 \x01(\tR\x11provisionalUserId\x12\x19\n" +
	"\bauth_key\x18\x03 \x01(\tR\aauthKey\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\"\x8f\x01\n" +
	"\x13VerifyPhoneResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1e\n" +
	"\vis_new_user\x18\x03 \x01(\bR\tisNewUser\x12)\n" +
	"\x10initial_password\x18\x04 \x01(\tR\x0finitialPassword\")\n" +
	"\x15CheckAuthTokenRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"G\n" +
	"\x16CheckAuthTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"U\n" +
	"\x18LoginWithPasswordRequest\x12\x1d\n" +
	"\n" +
	"phone_e164\x18\x01 \x01(\tR\tphoneE164\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"J\n" +
	"\x19LoginWithPasswordResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"S\n" +
	"\x15ChangePasswordRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"2\n" +
	"\x16ChangePasswordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xde\x02\n" +
	"\x11UpdateUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12&\n" +
	"\fdisplay_name\x18\x02 \x01(\tH\x00R\vdisplayName\x88\x01\x01\x12\x1b\n" +
	"\x06locale\x18\x03 \x01(\tH\x01R\x06locale\x88\x01\x01\x12\x1f\n" +
	"\btimezone\x18\x04 \x01(\tH\x02R\btimezone\x88\x01\x01\x12\"\n" +
	"\n" +
	"birth_date\x18\x05 \x01(\tH\x03R\tbirthDate\x88\x01\x01\x12\x15\n" +
	"\x03sex\x18\x06 \x01(\tH\x04R\x03sex\x88\x01\x01\x126\n" +
	"\x14onboarding_completed\x18\a \x01(\bH\x05R\x13onboardingCompleted\x88\x01\x01B\x0f\n" +
	"\r_display_nameB\t\n" +
	"\a_localeB\v\n" +
	"\t_timezoneB\r\n" +
	"\v_birth_dateB\x06\n" +
	"\x04_sexB\x17\n" +
	"\x15_onboarding_completed\"\x93\x04\n" +
	"\fUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"phone_e164\x18\x02 \x01(\tR\tphoneE164\x12F\n" +
	"\x11phone_verified_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0fphoneVerifiedAt\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12W\n" +
	"\x17onboarding_completed_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x15onboardingCompletedAt\x88\x01\x01\x12\x16\n" +
	"\x06locale\x18\a \x01(\tR\x06locale\x12\x1a\n" +
	"\btimezone\x18\b \x01(\tR\btimezone\x12!\n" +
	"\fdisplay_name\x18\t \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"birth_date\x18\n" +
	" \x01(\tR\tbirthDate\x12\x10\n" +
	"\x03sex\x18\v \x01(\tR\x03sex\x12\x19\n" +
	"\bis_admin\x18\f \x01(\bR\aisAdminB\x1a\n" +
	"\x18_onboarding_completed_at\",\n" +
	"\x14ValidateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"c\n" +
	"\x15ValidateTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_type\x18\x03 \x01(\tR\buserType\"P\n" +
	"\x1eCheckProvisionalOrphansRequest\x12.\n" +
	"\x13provisional_user_id\x18\x01 \x01(\tR\x11provisionalUserId\">\n" +
	"\x1fCheckProvisionalOrphansResponse\x12\x1b\n" +
	"\tis_orphan\x18\x01 \x01(\bR\bisOrphan\"N\n" +
	"\x1cDeleteProvisionalUserRequest\x12.\n" +
	"\x13provisional_user_id\x18\x01 \x01(\tR\x11provisionalUserId\"\x1f\n" +
	"\x1dDeleteProvisionalUserResponse2\xd0\a\n" +
	"\vUserService\x12D\n" +
	"\vPrepareAuth\x12\x19.users.PrepareAuthRequest\x1a\x1a.users.PrepareAuthResponse\x12M\n" +
	"\x0eResolveAuthKey\x12\x1c.users.ResolveAuthKeyRequest\x1a\x1d.users.ResolveAuthKeyResponse\x12b\n" +
	"\x15CreateProvisionalUser\x12#.users.CreateProvisionalUserRequest\x1a$.users.CreateProvisionalUserResponse\x12D\n" +
	"\vVerifyPhone\x12\x19.users.VerifyPhoneRequest\x1a\x1a.users.VerifyPhoneResponse\x125\n" +
	"\aGetUser\x12\x15.users.GetUserRequest\x1a\x13.users.UserResponse\x12;\n" +
	"\n" +
	"UpdateUser\x12\x18.users.UpdateUserRequest\x1a\x13.users.UserResponse\x12J\n" +
	"\rValidateToken\x12\x1b.users.ValidateTokenRequest\x1a\x1c.users.ValidateTokenResponse\x12h\n" +
	"\x17CheckProvisionalOrphans\x12%.users.CheckProvisionalOrphansRequest\x1a&.users.CheckProvisionalOrphansResponse\x12b\n" +
	"\x15DeleteProvisionalUser\x12#.users.DeleteProvisionalUserRequest\x1a$.users.DeleteProvisionalUserResponse\x12M\n" +
	"\x0eCheckAuthToken\x12\x1c.users.CheckAuthTokenRequest\x1a\x1d.users.CheckAuthTokenResponse\x12V\n" +
	"\x11LoginWithPassword\x12\x1f.users.LoginWithPasswordRequest\x1a .users.LoginWithPasswordResponse\x12M\n" +
	"\x0eChangePassword\x12\x1c.users.ChangePasswordRequest\x1a\x1d.users.ChangePasswordResponseB1Z/github.com/helthtech/core-users/pkg/proto/usersb\x06proto3"

var (
	file_users_proto_rawDescOnce sync.Once
	file_users_proto_rawDescData []byte
)

func file_users_proto_rawDescGZIP() []byte {
	file_users_proto_rawDescOnce.Do(func() {
		file_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_proto_rawDesc), len(file_users_proto_rawDesc)))
	})
	return file_users_proto_rawDescData
}

var file_users_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_users_proto_goTypes = []any{
	(*PrepareAuthRequest)(nil),              // 0: users.PrepareAuthRequest
	(*PrepareAuthResponse)(nil),             // 1: users.PrepareAuthResponse
	(*ResolveAuthKeyRequest)(nil),           // 2: users.ResolveAuthKeyRequest
	(*ResolveAuthKeyResponse)(nil),          // 3: users.ResolveAuthKeyResponse
	(*CreateProvisionalUserRequest)(nil),    // 4: users.CreateProvisionalUserRequest
	(*CreateProvisionalUserResponse)(nil),   // 5: users.CreateProvisionalUserResponse
	(*VerifyPhoneRequest)(nil),              // 6: users.VerifyPhoneRequest
	(*VerifyPhoneResponse)(nil),             // 7: users.VerifyPhoneResponse
	(*CheckAuthTokenRequest)(nil),           // 8: users.CheckAuthTokenRequest
	(*CheckAuthTokenResponse)(nil),          // 9: users.CheckAuthTokenResponse
	(*LoginWithPasswordRequest)(nil),        // 10: users.LoginWithPasswordRequest
	(*LoginWithPasswordResponse)(nil),       // 11: users.LoginWithPasswordResponse
	(*ChangePasswordRequest)(nil),           // 12: users.ChangePasswordRequest
	(*ChangePasswordResponse)(nil),          // 13: users.ChangePasswordResponse
	(*GetUserRequest)(nil),                  // 14: users.GetUserRequest
	(*UpdateUserRequest)(nil),               // 15: users.UpdateUserRequest
	(*UserResponse)(nil),                    // 16: users.UserResponse
	(*ValidateTokenRequest)(nil),            // 17: users.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),           // 18: users.ValidateTokenResponse
	(*CheckProvisionalOrphansRequest)(nil),  // 19: users.CheckProvisionalOrphansRequest
	(*CheckProvisionalOrphansResponse)(nil), // 20: users.CheckProvisionalOrphansResponse
	(*DeleteProvisionalUserRequest)(nil),    // 21: users.DeleteProvisionalUserRequest
	(*DeleteProvisionalUserResponse)(nil),   // 22: users.DeleteProvisionalUserResponse
	(*timestamppb.Timestamp)(nil),           // 23: google.protobuf.Timestamp
}
var file_users_proto_depIdxs = []int32{
	23, // 0: users.UserResponse.phone_verified_at:type_name -> google.protobuf.Timestamp
	23, // 1: users.UserResponse.created_at:type_name -> google.protobuf.Timestamp
	23, // 2: users.UserResponse.updated_at:type_name -> google.protobuf.Timestamp
	23, // 3: users.UserResponse.onboarding_completed_at:type_name -> google.protobuf.Timestamp
	0,  // 4: users.UserService.PrepareAuth:input_type -> users.PrepareAuthRequest
	2,  // 5: users.UserService.ResolveAuthKey:input_type -> users.ResolveAuthKeyRequest
	4,  // 6: users.UserService.CreateProvisionalUser:input_type -> users.CreateProvisionalUserRequest
	6,  // 7: users.UserService.VerifyPhone:input_type -> users.VerifyPhoneRequest
	14, // 8: users.UserService.GetUser:input_type -> users.GetUserRequest
	15, // 9: users.UserService.UpdateUser:input_type -> users.UpdateUserRequest
	17, // 10: users.UserService.ValidateToken:input_type -> users.ValidateTokenRequest
	19, // 11: users.UserService.CheckProvisionalOrphans:input_type -> users.CheckProvisionalOrphansRequest
	21, // 12: users.UserService.DeleteProvisionalUser:input_type -> users.DeleteProvisionalUserRequest
	8,  // 13: users.UserService.CheckAuthToken:input_type -> users.CheckAuthTokenRequest
	10, // 14: users.UserService.LoginWithPassword:input_type -> users.LoginWithPasswordRequest
	12, // 15: users.UserService.ChangePassword:input_type -> users.ChangePasswordRequest
	1,  // 16: users.UserService.PrepareAuth:output_type -> users.PrepareAuthResponse
	3,  // 17: users.UserService.ResolveAuthKey:output_type -> users.ResolveAuthKeyResponse
	5,  // 18: users.UserService.CreateProvisionalUser:output_type -> users.CreateProvisionalUserResponse
	7,  // 19: users.UserService.VerifyPhone:output_type -> users.VerifyPhoneResponse
	16, // 20: users.UserService.GetUser:output_type -> users.UserResponse
	16, // 21: users.UserService.UpdateUser:output_type -> users.UserResponse
	18, // 22: users.UserService.ValidateToken:output_type -> users.ValidateTokenResponse
	20, // 23: users.UserService.CheckProvisionalOrphans:output_type -> users.CheckProvisionalOrphansResponse
	22, // 24: users.UserService.DeleteProvisionalUser:output_type -> users.DeleteProvisionalUserResponse
	9,  // 25: users.UserService.CheckAuthToken:output_type -> users.CheckAuthTokenResponse
	11, // 26: users.UserService.LoginWithPassword:output_type -> users.LoginWithPasswordResponse
	13, // 27: users.UserService.ChangePassword:output_type -> users.ChangePasswordResponse
	16, // [16:28] is the sub-list for method output_type
	4,  // [4:16] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_users_proto_init() }
func file_users_proto_init() {
	if File_users_proto != nil {
		return
	}
	file_users_proto_msgTypes[15].OneofWrappers = []any{}
	file_users_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_proto_rawDesc), len(file_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_proto_goTypes,
		DependencyIndexes: file_users_proto_depIdxs,
		MessageInfos:      file_users_proto_msgTypes,
	}.Build()
	File_users_proto = out.File
	file_users_proto_goTypes = nil
	file_users_proto_depIdxs = nil
}
